version: '3.8'

services:
  llm-service-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    image: llm-service:cpu-latest
    container_name: llm-service-cpu
    ports:
      - "8001:8001"
    environment:
      - LOCAL_MODEL_PATH=./weights
      - DEVICE=cpu
      - USE_QUANTIZATION=false
      - LLM_SERVICE_HOST=0.0.0.0
      - LLM_SERVICE_PORT=8001
    volumes:
      # Optional: Mount logs directory for persistence
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - cpu

  llm-service-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    image: llm-service:gpu-latest
    container_name: llm-service-gpu
    ports:
      - "8001:8001"
    environment:
      - LOCAL_MODEL_PATH=./weights
      - DEVICE=cuda
      - USE_QUANTIZATION=false
      - LLM_SERVICE_HOST=0.0.0.0
      - LLM_SERVICE_PORT=8001
    volumes:
      # Optional: Mount logs directory for persistence
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - gpu

networks:
  default:
    name: llm-service-network
