[project]
name = "d-ai-token-visualizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "reflex>=0.7.14",
    "python-dotenv>=1.1.1",
    "httpx>=0.27.0",
    "plotly>=5.0.0",
    "networkx>=3.5",
]
